### ISSUE TITLE
[deming][Docker] with PostgreSQL error in table controls.score wrong type in HomeController.php (L138)

### ISSUE THREAD

**Issue by MCF241** [dbarzin/deming#1]
Bonjour,

J'ai créé une images docker et un container pour Deming sur PostgreSQL.
Au lancement de l'application après le login j'ai une erreur:

`Illuminate\Database\QueryException
SQLSTATE[42883]: Undefined function: 7 ERROR: operator does not exist: character varying = integer LINE 18: (c2.score=1 or c2.score =2); ^ HINT: No operator matches the given name and argument types. You might need to add explicit type casts. (SQL: select c2.measure_id, c2.id, c2.clause, c2.name, c2.plan_date from controls c2, ( select max(id) as id from controls where realisation_date is not null group by measure_id ) as c1 where c1.id = c2.id and (c2.score=1 or`

En suivant les informations données par la page d'erreur Laravel on se rend compte que l'erreur vient du type de donnée (CHAR au lieu de INT) dans la colonnes `score` de la table `controls`. Cela a pour conséquence de rejeter la requête dans le fichier HomeControllers.php à la ligne 138.

Ma question est la suivante; faut-il utiliser le contournement comme je le décris ci-dessous ou si il est plus prudent de modifier le type de la colonne controls.score dans la table de `CHAR` a `INT` ?. Cette colonne ne semblant contenir que des `NULL` ou des `INT`, cela semblerais plus logique.

**Contournement**
Requête SQL dans `/var/www/deming/app/Http/Controllers/HomeController.php` ligne 138 a changer :

`(c2.score=1 or c2.score=2);"));`

Par:

`(c2.score='1' or c2.score='2');"));`

ou

`(CAST(c2.score AS int)=1 or CAST(c2.score as int)=2);"));`

**Comment by MCF241** [comment]
Les images Docker et le conteneur sont créés sous MacOS X Monterey sur la machine M1.

La commande `php artisan deming:generateTests` crée des lignes dupliquées dans la table `deming.controls` puis `next_id` pointe vers les infos dupliquées (**est-ce normal ?**).

Donc => realization_date, observations, score, note et next_id sont mis à `NULL` dans le duplicata.

**Comment by dbarzin** [comment]
Oui, c'est normal. C'est une liste chaînée dont le dernier élément est NULL. 
Le denier contrôle n'est pas encore réalisé (realization_date=null), il n'y a pas encore d'observation ni de note.

**Comment by dbarzin** [comment]
Le score est un entier, il y avait une erreur dans la création de la DB.
pour mettre à jour : 

    git pull
    composer update
    php artisan migrate

Merci !

**Comment by MCF241** [comment]
Merci pour la réponse. Toutefois, dans mon cas, comme la base a été déjà initialisée, PostgreSQL rejet la migration du type de colonne.

Avant d'appliquer votre mise à jour, il est impératif d'effectuer la modification dans la base Postgres ainsi:

`ALTER TABLE controls
ALTER COLUMN score TYPE int USING score::integer;`

**Comment by dbarzin** [comment]
Laravel va migrer la base de données lors de l'exécution de la commande 

   php artisan migrate

Ce qui aura pour effet de changer le type de la colonne.

**Comment by MCF241** [comment]
J'ai recréer mon images docker (v.1.01 pour moi) avec succès.
Puis executé le :
`docker-compose up --build -d`
Puis saisi : 
`docker exec -it deming /bin/bash`

Ensuite j'ai executer les commandes que vous avez soumises.
Mais lors de ma première tentative, j'ai obtenu un message d'erreur disant que le type de la colonne ne pouvait être changé sans `USING score::integer;`.

Une fois cette commande saisie `php artisan migrate` a pu s'executer normalement.

Toutefois cette erreur ne venais peut-être d'autre chose car je n'ai pas pu reproduire l'erreur. Je devrais tester dans la semaine avec une installation __*From Scratch*__ :)

Si cela vous intéresse je pourrais vous envoyer, par courriel, ma docker file et les éléments utilisés pour crée le container _deming PostGreSQL_.

Je peut aussi créer un version __*Bundled*___ avec deming et PostgreSQL dans la même image ?

**Comment by dbarzin** [comment]
Tu peux faire un pull request dans le projet avec la documentation ?

**Comment by MCF241** [comment]
Malheureusement je ne suis pas, non plus, un utilisateur chevronné de GIT :(

J'essaye dans la semaine, après une mise à jour de mes connaissances sur GIT (sorry, i'm old school)

**Comment by dbarzin** [comment]
Tu vas y arriver !
