### ISSUE TITLE
Page d'accueil / tableau de bord

### ISSUE THREAD

**Issue by JinxCH73** [dbarzin/deming#13]
Bonjour,

J'ai 10 domaines au niveau de la page d'accueil / tableau de bord. 
Or, en cliquant dessus, je n'en ai que 5.

**Comment by dbarzin** [comment]
S'il n'y a pas de mesures de sécurité dans un domaine ou qu'aucune mesure de sécurité de ce domaine n'est planifiée alors le domaine n'est pas pris en compte dans le comptage sur le tableau de bord.

**Comment by JinxCH73** [comment]
Oui je me retrouve avec 10 domaines sur le tableau de bord de la page d'accueil alors qu'il n'y en a que 5 : 
![image](https://github.com/dbarzin/deming/assets/115431192/9eec9fa9-4139-40f3-8cd1-7b34d55e8683)
![image](https://github.com/dbarzin/deming/assets/115431192/ffb908fc-1630-4c68-9362-45099a4a7c65)

**Comment by dbarzin** [comment]
Peux-tu exécuter ces commandes et me donner le résultat : 

    php artisan db

    select id, description from domains;
    select domain_id, max(id) from controls where realisation_date is null group by domain_id;

Merci.

**Comment by JinxCH73** [comment]
Oui, voici : 
mysql> select id, description from domains;
+----+------------------------------+
| id | description                  |
+----+------------------------------+
| 25 | SMSI                         |
| 26 | Sécurité organisationnelle   |
| 27 | Sécurité des personnes       |
| 28 | Sécurité physique            |
| 29 | Sécurité technique           |
+----+------------------------------+
5 rows in set (0.00 sec)

mysql> select domain_id, max(id) from controls where realisation_date is null group by domain_id;
+-----------+---------+
| domain_id | max(id) |
+-----------+---------+
|        25 |     311 |
|        26 |     141 |
|        27 |     165 |
|        28 |     207 |
|        29 |     309 |
+-----------+---------+
5 rows in set (0.00 sec)

**Comment by dbarzin** [comment]
Le problèmes est-il toujours présent ? C'est difficilement explicable, la requête db renvoie bien 5 éléments.
Le compteur devrait également afficher 5.

**Comment by JinxCH73** [comment]
Oui toujours à 10 sur le tableau de bord de la page d'accueil
![image](https://github.com/dbarzin/deming/assets/115431192/89184dd6-5264-4d62-8edd-dcc7371437d7)

**Comment by dbarzin** [comment]
N'aurais)tu pas deux instances de Deming qui tournent l'une avec les mesures de la 27001:2013 et l'autre avec les mesures de la 27001:2022 ?

**Comment by JinxCH73** [comment]
Non, je n'ai sélectionné à l'install que la 2022.

**Comment by dbarzin** [comment]
Vous avez bien suivi la procédure d'installation ? Pas de spécificités ?
Pouvez-vous envoyer une capture d'écran de toute la page principal ?

**Comment by JinxCH73** [comment]
![image](https://github.com/dbarzin/deming/assets/115431192/c2e11e10-9234-4bf8-950a-88ea4cb19a3c)

**Comment by JinxCH73** [comment]
Oui rien de spécial, la procédure d'installation.

**Comment by dbarzin** [comment]
C'est corrigé !
Merci pour ton aide.
Didier

**Comment by JinxCH73** [comment]
Merci !
