### ISSUE TITLE
problème lors de la creation d'un measurement

### ISSUE THREAD

**Issue by sudolilya** [dbarzin/deming#130]
### Discussed in https://github.com/dbarzin/deming/discussions/129

<div type='discussions-op-text'>

<sup>Originally posted by **sudolilya** August 14, 2024</sup>
Bonjour Didier,

En premier, merci beaucoup pour ce que vous aviez mis en place pour la communauté Sécurité.

Je viens de constater qu'avec la nouvelle version le bouton +New measurement retourne un message d'erreur que stipulant que la view **create**. n'existe pas: resources/views/measures/create.blade.php (voir PJ ci joint).

J'ai vérifié sur mon repertoire et sur le git deming même chose:

la page create n'existe pas sur le control
https://github.com/dbarzin/deming/tree/7a1301c103be5733e3ab148422a3ad74efb8348a/resources/views/controls
Existe sur le measures:
https://github.com/dbarzin/deming/tree/7a1301c103be5733e3ab148422a3ad74efb8348a/resources/views/measures

or que le message retourn Not found au moment de rajouter New measurement mais new control fonctionne bien.

Merci par avance.
Lylia

</div>

**Comment by dbarzin** [comment]
Merci, la vue a été ajoutée.

**Comment by dbarzin** [comment]
https://github.com/dbarzin/deming/pull/132

**Comment by sudolilya** [comment]
Merci ! ça fonctionne trés bien.
