### ISSUE TITLE
Question : A quoi sert "Note" svp ?

### ISSUE THREAD

**Issue by cece46** [dbarzin/deming#14]
Dans la documentation, il n'est pas précisé à quoi sert NOTE (entier). En tout cas, cet élément sort à l'édition de rapport. 
Pouvez-vous m'éclairer ?

**Comment by dbarzin** [comment]
C'est le résultat de l'évaluation de la mesure de sécurité. 
C'est par exemple le nombre de poste de travail sans antivirus, le nombre d'erreur identifiées, ...
