### ISSUE TITLE
ISSUE executing "composer install"

### ISSUE THREAD

**Issue by kpaka19** [dbarzin/deming#16]
Hello @dbarzin ,
Hope you doing well; Thank you for sharing this incredible app.
Unfortunately I've got an issue during running of this command : composer install.
here is the output: 
PHP Fatal error:  Declaration of Composer\IO\BaseIO::emergency(Stringable|string $message, array $context = []): void must be compatible with Psr\Log\LoggerInterface::emergency($message, array $context = []) in /usr/share/php/Composer/IO/BaseIO.php on line 163

Fatal error: Declaration of Composer\IO\BaseIO::emergency(Stringable|string $message, array $context = []): void must be compatible with Psr\Log\LoggerInterface::emergency($message, array $context = []) in /usr/share/php/Composer/IO/BaseIO.php on line 163

Thank you in advance for your reply.
Best regards,

**Comment by dbarzin** [comment]
Hello,
Have you followed the installation procedure ? 
Do you use Ubuntu 22.04 LTS ?

Could you execute these commands : 

    uname -a
    composer -V
    php -v

Thanks,
Didier

**Comment by kpaka19** [comment]
It's ok now the issue was linked to the version of ubuntu.
I've made an upgrade to 22.04 and it works fine.
