### ISSUE TITLE
Erreur quand on clique sur un user dans list users 

### ISSUE THREAD

**Issue by sudolilya** [dbarzin/deming#166]
j'ai une erreur à la ligne 95 quand je clique sur un user x dans la liste des user dans deming.

Merci par avance,
Lylia

**Comment by dbarzin** [comment]
Ne se produit plus. Sans doute corrigé précédemment.

**Comment by sudolilya** [comment]
testé ça fonctionne.

Merci

**Comment by sudolilya** [comment]
testé avec la nouvelle version.

ça fonctionne,

Merci.
