### ISSUE TITLE
Intégration du CSF 2.0 avec l’ajout de #Govern ?

### ISSUE THREAD

**Issue by sudolilya** [dbarzin/deming#168]
Peut on rajouter le Govern dans la liste des attributes

Cybersecurity Concepts: #Identify #Protect #Detect #Respond #Recover #Govern

merci par avance.
Lylia

**Comment by dbarzin** [comment]
Cela a été ajouté, mais cette liste est remplie lors de la création initiale de la base de données.
Si la base de données est déjà créée, il faut l'ajouter via l'interface web.

**Comment by sudolilya** [comment]
Merci, oui c'est corrigé je l'ai ajouté depuis l'interface web.
