### ISSUE TITLE
Le bouton plan d’un contrôle nous mène sur une page appelée control planning alors que c’est measurement planning

### ISSUE THREAD

**Issue by sudolilya** [dbarzin/deming#169]
Sur la page controls quand je clique sur le bouton plan d’un contrôle nous mène sur une page appelée control planning alors que c’est measurement planning.

**Comment by dbarzin** [comment]
Corrigé ici : https://github.com/dbarzin/deming/commit/b10eb013a5530aff66be96949fda52cb95c87ed7
