### ISSUE TITLE
Problem with click on date using Chrome Version 115.0.5790.102

### ISSUE THREAD

**Issue by BertrandLefebvre** [dbarzin/deming#17]
For example on control section, i cant click on the date. No problem with Firefox.

**Comment by dbarzin** [comment]
Tested successfully  with Chromium Version 114.0.5735.198 (Build officiel) snap (64 bits)

**Comment by dbarzin** [comment]
Tested successfully with Google-Chrome Version 115.0.5790.102 (Build officiel) (64 bits)

Could not reproduce the issue.

**Comment by BertrandLefebvre** [comment]
I reproduce the issue after adding a user and I have to close my chrome tab to make it work again. And I wasn't able to reproduce it ...

I had the error on the  content-wrapper div and on the line error :

***@***.***
***@***.***


Cordialement,

Bertrand Lefebvre
Responsable de Projets

***@***.***
ZI Est - Angle des Rues Stéphenson et Guérin
62217 Tilloy les Mofflaines
* Standard: +33 (0) 3 21 60 94 00
* Mobile: +33 (0) 6 12 98 53 14
* Fax: +33 (0) 3 21 22 06 83
site web : http://www.actemium.com<http://www.actemium.com/>

 [Description : Image1]


 Allégez votre empreinte écologique, n'imprimez pas ce courriel!
oooO
(   )
\ (     Oooo
 \_)    (   )
           ) /
        (_/

De : Didier Barzin ***@***.***>
Envoyé : mardi 25 juillet 2023 12:57
À : dbarzin/deming ***@***.***>
Cc : LEFEBVRE Bertrand ***@***.***>; Author ***@***.***>
Objet : Re: [dbarzin/deming] Problem with click on date using Chrome Version 115.0.5790.102 (Issue #17)


Tested successfully with Chromium Version 114.0.5735.198 (Build officiel) snap (64 bits)

-

**Comment by dbarzin** [comment]
Pas reproductible
