### ISSUE TITLE
Non report de la référence de la clause lors de la création d'un nouveau contrôle après une validation

### ISSUE THREAD

**Issue by jiemji** [dbarzin/deming#180]
Un audité traite le contrôle et indique le score de conformité (sa valeur n'a pas d'incidence sur le bogue)
L'utilisateur voit le contrôle traité et clique sur le sablier pour valider.
Si Acceptation du score indiqué par l'Audité, il y a création d'une duplication du contrôle qui porte la réf du contrôle initial et le contrôle initial est affiché avec un un champs clause vide ; la nouvelle ligne porte la ref de la clause, par contre.
Si Rejet du contrôle, celui perd sa référence (le champs clause est vide)

![Screenshot - Deming - Controles](https://github.com/user-attachments/assets/d1efb7cc-d65c-457c-b21b-7f22bd3eb701)

**Comment by dbarzin** [comment]
Je n'arrive pas à reproduire le problème décrit.
Utilisez-vous la dernière version du projet ?

**Comment by jiemji** [comment]
Merci de votre retour
le version a été installé vendredi (2024-10-R2) sur une VM ubuntu server headless 22.04.5 ne contenant que l'application Deming (et ses dépendances)

**Comment by dbarzin** [comment]
> Un audité traite le contrôle et indique le score de conformité (sa valeur n'a pas d'incidence sur le bogue) L'utilisateur voit le contrôle traité et clique sur le sablier pour valider. Si Acceptation du score indiqué par l'Audité, il y a création d'une duplication du contrôle qui porte la réf du contrôle initial et le contrôle initial est affiché avec un un champs clause vide ; la nouvelle ligne porte la ref de la clause, par contre. Si Rejet du contrôle, celui perd sa référence (le champs clause est vide)
> 
> ![Screenshot - Deming - Controles](https://private-user-images.githubusercontent.com/50717238/376227007-d1efb7cc-d65c-457c-b21b-7f22bd3eb701.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMDUxOTYsIm5iZiI6MTcyOTAwNDg5NiwicGF0aCI6Ii81MDcxNzIzOC8zNzYyMjcwMDctZDFlZmI3Y2MtZDY1Yy00NTdjLWIyMWItN2YyMmJkM2ViNzAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDE1MDgxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5MmJiMTdlNTYyNGJmMTQ0ZTcyYmQ4ZTBlNDQ2NGE3ZTYyZGE4NjAwNDllYmU4OTYyYTY2ZjIxMzE4ZjNhYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.J3meqsOo1-826jNoJtLKmpan3x_xULMTU73fWfA-DCk)

Dans l'écran ci-dessus, je ne vois pas de contrôle en double.

**Comment by jiemji** [comment]
> Dans l'écran ci-dessus, je ne vois pas de contrôle en double.

Dans le sens où les dates sont différentes ? le contrôle "amélioration continue" sans clause a été généré après validation du contrôle "Amélioration continue" contenant un numéro de clause. Ce ne sont pas 2 contrôles créés indépendamment. (les différentes de dates proviennent des test qui ont suivi pour comprendre)

**Comment by dbarzin** [comment]
J'ai proursuivit le test précédent. Paul a proposé une nouvelle obervation qui a été acceptée. 
Voici la liste des contrôles : 

![image](https://github.com/user-attachments/assets/46bc678b-502d-4f37-9d8a-280927115424)

et effectivement, le sablier est présent et il manque les clauses.

**Comment by dbarzin** [comment]
Corrigé ici : https://github.com/dbarzin/deming/pull/185

**Comment by jiemji** [comment]
merci. ça fonctionne
