### ISSUE TITLE
SQL error

### ISSUE THREAD

**Issue by cbocapbp** [dbarzin/deming#184]
try to delete control mesure, for example : https://myfqdndomain/alice/delete/11

got an SQL error in laravel : 

Illuminate\Database\QueryException

SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`demingbase`.`control_measure`, CONSTRAINT `control_measure_measure_id_foreign` FOREIGN KEY (`measure_id`) REFERENCES `measures` (`id`)) (Connection: mysql, SQL: delete from `measures` where `id` = 11)

app/Http/Controllers/MeasureController.php :381
Measure::destroy($request->id);

can you please try/catch this sql event and manage error in php framework ?

best regards

**Comment by dbarzin** [comment]
It is here : https://github.com/dbarzin/deming/pull/186
