### ISSUE TITLE
PGSQL Create database failed

### ISSUE THREAD

**Issue by yjacolin** [dbarzin/deming#19]
file: database/migrations/2022_05_15_030940_control_score_to_int.php 

When upgrading/creating a Pgsql database, the step "2022_05_15_030940_control_score_to_int" failed due to "Datatype mismatch: 7 ERROR:  column "score" cannot be cast automatically to type integer".

**Comment by dbarzin** [comment]
It has been tested with mysql only. I suspect that the command used to change an column type from string to int does not work with PGSQL.

**Comment by dbarzin** [comment]
It is possible to make conditional tests in migration base on DB::getDriverName()

    if (DB::getDriverName() !== 'pgsql') {
        // code for PGSql
    } else {
        // code fo mySQL
    }

**Comment by yjacolin** [comment]
Thanks, here a PR: https://github.com/dbarzin/deming/pull/22

**Comment by dbarzin** [comment]
Approved.
