### ISSUE TITLE
Sending reports over SMTP 

### ISSUE THREAD

**Issue by mbsouth** [dbarzin/deming#192]
Exactly what I was looking for, thank you very much!

Feature request:
Sending messages, notifications or reports via **yourdomain.localhost**, as described in the installation manual (MailX and Postfix), is a shot in the foot:
- no SPF Record
- no DKIM signature
- DMARC not possible
- perhabs no public A or MX Record (yourdomain.localhost)

**99.99%** of these emails are classified as SPAM!

Why not send notifications or reports via an authenticated SMTP account whose server takes all security- and spam-relevant settings?
MailX and Postfix would then not be necessary.

mbsouth

**Comment by dbarzin** [comment]
Thank you for your feedback! You’re absolutely right about the issues with sending emails via **yourdomain.localhost** —without SPF, DKIM, or DMARC, these emails can easily be flagged as spam.

Using an authenticated SMTP account would indeed improve security and simplify configuration by eliminating the need for MailX and Postfix. I've marked this as an improvement for future releases.

Thanks again for the suggestion!

**Comment by dbarzin** [comment]
This is implemented here : https://github.com/dbarzin/deming/pull/197

**Comment by mbsouth** [comment]
It seems, that will be a WOW Experience!
Thanks!
