### ISSUE TITLE
[deming][Docker] Error with PostgreSQL in 'Radar'

### ISSUE THREAD

**Issue by MCF241** [dbarzin/deming#2]
J'ai créé une image docker et un conteneur pour Deming sur une machine MacOS X Monterey M1 et j'ai obtenu l'erreur suivante :

`SQLSTATE[42702]: Ambiguous column: 7 ERROR: column reference "measure_id" is ambiguous LINE 17: group by measure_id order by clause; ^ (SQL: select c1.id as control_id, c1.name as name, c1.clause as clause, c1.measure_id as measure_id, c1.domain_id as domain_id, c1.plan_date as plan_date, c1.realisation_date as realisation_date, c1.score as score, c2.plan_date as next_date, c2.id as next_id from controls c1 left join controls c2 on c1.next_id=c2.id where c2.realisation_date is null and c1.next_id is not null group by measure_id order by clause;)
`

La solution de contournement est la suivante pour faire fonctionner l'option radar :

Modification de la déclaration SQL dans `/var/www/deming/app/Http/Controllers/ControlController.php` à partir de la ligne 269

`group by measure_id order by clause;"`

par:

`group by c1.id, c2.plan_date, c1.measure_id, c2.id order by c1.clause;"`

**Comment by dbarzin** [comment]
Merci pour la correction.
