### ISSUE TITLE
PGSQL: INTERVAL needs simple quote

### ISSUE THREAD

**Issue by yjacolin** [dbarzin/deming#20]
https://github.com/dbarzin/deming/blob/main/app/Http/Controllers/HomeController.php#L108

I don't know for MySQL, but for PostgreSQL, it should be:
` where (c1.realisation_date is null) and (c1.plan_date < NOW() + INTERVAL \'30 DAY\')` 

Does it supported by MySQL?

**Comment by dbarzin** [comment]
This could be change. Could you submit a Pull Request ?
Thanks,
Didier

**Comment by yjacolin** [comment]
Here it is: https://github.com/dbarzin/deming/pull/21

Thanks!

**Comment by dbarzin** [comment]
Your PR does not work with mySQL. The other way is to compute the end date in PHP.
I will do it at lunch time.

**Comment by dbarzin** [comment]
Fixed
