### ISSUE TITLE
[Enhancement] Measurement in progress

### ISSUE THREAD

**Issue by ggs67** [dbarzin/deming#205]
It would be great to be able to set a control measurement into "In-Progress" state before the final "Make" and indicate this status by some color in the planning calendar

**Comment by dbarzin** [comment]
Great idea! We'll implement an "In-Progress" status for control measurements with a distinct color indicator in the planning calendar. Thanks for the suggestion!

**Comment by dbarzin** [comment]
This is available here : https://github.com/dbarzin/deming/pull/207/commits/0ae0ebfaf7e296511c5c034acb98994f1261eaee
