### ISSUE TITLE
Unable to delete measurement planning created by mistake by a user

### ISSUE THREAD

**Issue by ggs67** [dbarzin/deming#209]
One of my users used "Plan" instead of "Make" for a measurement and created a second open measurement for it. However when I delete it, Deming tells me that a control is attached to it, which makes sense of course.

So I have 2 planned open measurements for the same control and I want do delete one. I do not find a way to achieve this.

P.S.: IMHO, a "User" role should be able to "Make" but not "Plan" a control ?

**Comment by dbarzin** [comment]
When you click on "plan"  instead of "Make" for a measurement, it does not create a new measurement. 
You may only change the plan date, periodicity and users in charge of that measurement.

If you are administrator, you may remove any measurement.

**Comment by ggs67** [comment]
Well I don't know where he clicked on "Plan" in the control or measurement, but fact is that we have now 2 pending measurements, one (the new one) with today's date.

I tried to delete it, as administrator, but get a message in a red box stating that "a control is attached to that measurement" (roughly) and the measurement is not deleted.

**Comment by dbarzin** [comment]
The error message "There are controls associated with this measure !" is displayed when you try to delete a measure that has controls associated with it. You have to remove all associated controls before removing the measure.

**Comment by ggs67** [comment]
Ok, I found the problem. I clicked on the clause (i.e. control) in the measurement list instead of clicking the date (e.g. the measurement)

Thanks!
