### ISSUE TITLE
[Proposition ] possibilité exporter un action plan

### ISSUE THREAD

**Issue by sudolilya** [dbarzin/deming#214]
Bonjour,

ce n'est pas un bug mais juste une proposition de faire un export de l'action plan avec les informations du champs observation, action plan et responsable du measurement.

Merci.

**Comment by dbarzin** [comment]
Ce point se trouve dans la liste des améliorations. Les plans d'actions ne seront plus obligatoirement liés à un contrôle et il sera possible d'exporter dans une feuille de calcul l'ensemble des informations se trouvant dans les plans d'action.

**Comment by dbarzin** [comment]
C'est disponible !
