### ISSUE TITLE
php8.3 - update install.md

### ISSUE THREAD

**Issue by TrackPixel** [dbarzin/deming#228]
Hello Didier,

I'm new to Github, so I'm not confident in updating the install.md file.

By default on ubuntu, php8.3 is installed, so please update the manual:

sudo a2dismod php8.1 ->  sudo a2dismod php8.3
sudo a2enconf php8.1-fpm -> sudo a2enconf php8.3-fpm

Thanks !

**Comment by dbarzin** [comment]
It is fixed https://github.com/dbarzin/deming/pull/229/commits/7feb621524516df2b993201c55e630f833de74ea 
Thanks !
