### ISSUE TITLE
PGSQL: how to manage insert script deming-27001:2022.sql?

### ISSUE THREAD

**Issue by yjacolin** [dbarzin/deming#23]
For my own test, I migrated deming-27001:2022.sql script to be supported by PostgreSQL. But, it won't work for MySQL (except if we remove objects quotes: table and attributes name). Unfortunately, deming uses protected column name (values in controls table). So we probably need to have two scripts to manage.

The good news is that PostgreSQL script are usually working on SQLite.

Do you have any counter-proposition? Are you willing to manage two scripts? Difference are:
* don't use LOCK / UNLOCK
* double quote object: ALTER TABLE "mytable"
* double '' if you are using simple quote in string: 'L''ambulance'

**Comment by dbarzin** [comment]
I propose to put the values in a CSV file and import them using a [Laravel console command script](https://laravel.com/docs/master/artisan). So it can be independent of the target database.

**Comment by yjacolin** [comment]
Thanks, so I am not skilled for this :) I am not a Laravel developper.

**Comment by dbarzin** [comment]
OK, I will do it. Simple PHP development.

**Comment by dbarzin** [comment]
These commands will create a test environment for any target database :

    php artisan migrate:fresh --seed
    php artisan db:seed --class=AttributeSeeder
    php artisan db:seed --class=DomainSeeder
    php artisan db:seed --class=MeasureSeeder
    php artisan deming:generateTests

**Comment by yjacolin** [comment]
Only the last command failed:

```
$ php artisan deming:generateTests
Remove all controls and documents

   Illuminate\Database\QueryException 

  SQLSTATE[42704]: Undefined object: 7 ERROR:  unrecognized configuration parameter "foreign_key_checks" (Connection: pgsql, SQL: SET foreign_key_checks=0)

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:795
    791▕         // If an exception occurs when attempting to run a query, we'll format the error
    792▕         // message to include the bindings with SQL, which will make this exception a
    793▕         // lot more helpful to the developer instead of just the database's errors.
    794▕         catch (Exception $e) {
  ➜ 795▕             throw new QueryException(
    796▕                 $this->getName(), $query, $this->prepareBindings($bindings), $e
    797▕             );
    798▕         }
    799▕     }

      +7 vendor frames 

  8   app/Console/Commands/GenerateTestData.php:37
      Illuminate\Support\Facades\Facade::__callStatic("statement")
      +12 vendor frames 

  21  artisan:35
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

```

**Comment by yjacolin** [comment]
I confirm. Thanks!
