### ISSUE TITLE
PGSQL: Analyze > Control dashboard trigger SQL error

### ISSUE THREAD

**Issue by yjacolin** [dbarzin/deming#24]
There are two issues:

First column "measure_id"  in group by is ambiguous, and then attributes in SELECT clause and in ORDER BY should be in GROUP BY or use in an aggregate function.

`select "c1"."id" as "control_id", "c1"."name" as "name", "c1"."clause" as "clause", "c1"."measure_id" as "measure_id", "c1"."domain_id" as "domain_id", "c1"."plan_date" as "plan_date", "c1"."realisation_date" as "realisation_date", "c1"."score" as "score", "c2"."plan_date" as "next_date", "c2"."id" as "next_id" from "controls" as "c1" left join "controls" as "c2" on "c1"."next_id" = "c2"."id" where "c2"."realisation_date" is null and "c1"."next_id" is not null and "c1"."realisation_date" <= 2023-07-27 group by "measure_id" order by "clause" asc`

**Comment by dbarzin** [comment]
Should be fixed.
Thanks,
Didier

**Comment by yjacolin** [comment]
thanks, the ambiguous column error is fixed but I still get 
> Grouping error: 7 ERROR: column "c1.id" must appear in the GROUP BY clause or be used in an aggregate function

Attributes in SELECT clause and in ORDER BY should be in the GROUP BY or use in an aggregate function in PostgreSQL. I don't know how it works in MySQL!

**Comment by dbarzin** [comment]
Could you give me the correct SQL command in PostgreSQL ?

**Comment by dbarzin** [comment]
As string_agg does not exists in mySQL, I propose to test the database drive and submit the corresponding SQL statement to the database.

**Comment by yjacolin** [comment]
Depending on what you planned to get, you can use max("name") also!

**Comment by dbarzin** [comment]
I have push another SQL query that works with mySQL.
