### ISSUE TITLE
Translation for english or german

### ISSUE THREAD

**Issue by FWITC** [dbarzin/deming#3]
hey your tool looks great but i hava a little bit of problems witch france. Do you plan a translation?

**Comment by dbarzin** [comment]
Hello,
Yes, it is planned and also the migration to ISO 27001:2022.
Please come back at end January 2023.
Thanks,
Didier

**Comment by dbarzin** [comment]
English translation is now available !

**Comment by FWITC** [comment]
cool thanks i make a puul request today but how i can setup or change to english?

**Comment by dbarzin** [comment]
It will be available today with some minor fixes.

**Comment by dbarzin** [comment]
To change language, click on the gear on the to right of the screen.

**Comment by FWITC** [comment]
> To change language, click on the gear on the to right of the screen.

this button not working is there a other table or command at a new installation i have to execute?

**Comment by dbarzin** [comment]
Did you update the code with git pull ?

**Comment by FWITC** [comment]
> Did you update the code with git pull ?

I delete my old instance and create a complete new one

**Comment by dbarzin** [comment]
have you done it recently ?

**Comment by FWITC** [comment]
> have you done it recently ?

Yes only one hour before reply

**Comment by FWITC** [comment]
Oh just forget I can’t change to France which is not a problem. Only the sql dump is in France which is ok

**Comment by dbarzin** [comment]
I have forgotten some labels on the welcome page. This is fixed.
Thanks,
Didier
