### ISSUE TITLE
Packaging for debian

### ISSUE THREAD

**Issue by bastien-roucaries** [dbarzin/deming#32]
Hi,

I can package demming for debian if needed. 

Do you agree as upstream with that.

I will use this bug report as a review pad

rouca

**Comment by dbarzin** [comment]
Yes of course !

**Comment by bastien-roucaries** [comment]
Do you want to comaintain it ? I can sponsor after a first upload

**Comment by dbarzin** [comment]
Yes, I will comaintain your contributions.

**Comment by dbarzin** [comment]
This is now available here : https://github.com/dbarzin/deming/blob/main/INSTALL.debian.md
