### ISSUE TITLE
Possible to declare a measures as "not applicable"

### ISSUE THREAD

**Issue by pep-un** [dbarzin/deming#33]
Hello, 

First, thank you for this project ! I may have a suggest for an improvement. 

When using some corporate framework, we may have to reject a Control not applicable for our context.
Could it be possible to implement a check box to declare a control as not applicable ? 

When checked, it should not be visible in Measurement, Analysis and Actions tab. 
It could also be nice to have a table with all rejected controls in the report as they often are reviewed for risk acceptation. 

Regards,

**Comment by dbarzin** [comment]
When a Control is not applicable, you may simply not plan it.
Then a Measurement is not created for that Control.
And it is not present in the Analysis and Action tab.

We could create a report with all Controls that planned and not planned.

**Comment by pep-un** [comment]
Thank you for the feedback, I will do as you suggest. 
A report on non-planned Conrols could be nice.

**Comment by dbarzin** [comment]
Will be available with the "scopes" :ok_hand:

**Comment by dbarzin** [comment]
It is available ! :sparkle:

**Comment by kikispas** [comment]
What is the french translation of "scopes" in the application ? "Domaines" ?

So, we create a new "scope" "not applicable" and we move all measures that does not concern us into this new scope, right ?

**Comment by dbarzin** [comment]
Le terme "scope" a été traduit par "périmètre" dans la version française.

Dans un contrôle, le périmètre désigne un ensemble d'assets concernés par celui-ci. Si tous les assets sont concernés, le champ peut rester vide.

Pour identifier les contrôles appliqués, il est possible dans la partie "rapports" de l'application de générer la déclaration d'applicabilité.

**Comment by kikispas** [comment]
Merci pour la réponse !

C'est dommage, je cherche l'inverse... J'aurais souhaité pouvoir "tagger" une mesure comme non applicable (avec un champ pour la justification de l'exclusion) et dans la DdA que l'on télécharge, avoir les colonnes "Applicable" oui/non + une colonne avec la justification de l'exclusion...

L'outil reste excellent pour planifier les contrôles, mais pour mon cas, qui concerne un tout petit périmètre à certifier, un seul asset dans une tpe, j'aurais adoré que cet outil me "prémache" une DdA sur laquelle m'appuyer pour la suite des opérations puis ensuite, la planifier des contrôles.

**Comment by dbarzin** [comment]
Pour faire la DdA, tu as juste besoin d'une feuille de calcul.
Tu peux extraire toutes les contrôles de Deming et ajouter une colonne  "Applicable" oui/non + une colonne avec la justification de l'exclusion...
