### ISSUE TITLE
Documents - size limit and scoring issue

### ISSUE THREAD

**Issue by thibaudpeter** [dbarzin/deming#39]
Hello, it is not possible anymore to save documents over 1Mb.
Also only meseaurements with green scores can have documents saved up (not when it is orange or red)

**Comment by dbarzin** [comment]
You need to set the value of upload_max_filesize and post_max_size in your php.ini :

; Maximum allowed size for uploaded files.
upload_max_filesize = 40M

; Must be greater than or equal to upload_max_filesize
post_max_size = 40M

After modifying php.ini file(s), you need to restart your HTTP server to use the new configuration.

**Comment by dbarzin** [comment]
Documents are save even if score is red or orange.

**Comment by dbarzin** [comment]
Intall procedure updated !

**Comment by thibaudpeter** [comment]
> You need to set the value of upload_max_filesize and post_max_size in your php.ini :
> 
> ; Maximum allowed size for uploaded files. upload_max_filesize = 40M
> 
> ; Must be greater than or equal to upload_max_filesize post_max_size = 40M
> 
> After modifying php.ini file(s), you need to restart your HTTP server to use the new configuration.

Amazing, thanks for the quick tip 

Tested with green and red scoring :)

**Comment by dbarzin** [comment]
Here is a control with a red score and an attached document : 
![image](https://github.com/dbarzin/deming/assets/43208232/7903c344-dbdb-48a1-a755-e1484b383f0b)
