### ISSUE TITLE
The /var/www/deming/bootstrap/cache directory must be present and writable.

### ISSUE THREAD

**Issue by bbreton09** [dbarzin/deming#4]
Bonjour, petite erreur lors du "composer install."
In PackageManifest.php line 177:

  The /var/www/deming/bootstrap/cache directory must be present and writable.

j'ai du créer le dossier 
mkdir -p bootstrap/cache

**Comment by dbarzin** [comment]
Merci, la commande a été ajoutée à la procédure d'installation.
