### ISSUE TITLE
Segregation between between Measurements inputs and Control scoring and validation

### ISSUE THREAD

**Issue by thibaudpeter** [dbarzin/deming#40]
Also, would it be possible for users to upload docuements and save their controls. (Measurements inputs )
Then the IT controller (audit/admin) validate/modify the measurement and attribute a score.

**Comment by dbarzin** [comment]
This is not on the roadmap at this time, it seems to be interesting. 
Do you have references to this process ?

**Comment by thibaudpeter** [comment]
Not on paper, but my previous employer had the best internal control tool ever..
As IT controls management should not be frozen, the tool gives room to manual edition per measurements..
Will try to write down the features/processes 

Owe you 2 coffes now haha

**Comment by dbarzin** [comment]
Validation process in available ! :tada:
