### ISSUE TITLE
The reports for Security measures and Controls might be inverted?

### ISSUE THREAD

**Issue by thibaudpeter** [dbarzin/deming#44]
I don't know if it is an expected behavior from the Report panel 
- The Controls Report is linked to the **Measurement list** tab
- The Security measures Report is linked to the **Control list** tab

From the Generate test data
When you exports the Security measures -> You get the 104 results (ISO27002)
When you exports the Controls -> You get the 310 results

**Comment by dbarzin** [comment]
Filenames where incorrect. It is fixed.
It was due to french-english translations. Have a look at definitions in the documentation : https://dbarzin.github.io/deming/index.fr/
Thanks,
Didier
