### ISSUE TITLE
New installation (Docker compose) - DB Cleaning

### ISSUE THREAD

**Issue by Emeric-hub** [dbarzin/deming#46]
Hi (Bonjour),

I just discover this project ... and ... woaaaaahhhh !!! 
What an incredible work you did !!!

I just found a few typo issues ...

a few strange labels ... see capture under ...

![image](https://github.com/dbarzin/deming/assets/79230405/abe585db-1940-4961-a6d0-36d175fcd4af)

Ok, en francais, c'est plus simple ...

Et si je souhaite juste une installation clean ... pour eviter d'avoir déja des checks en erreur (ou pas) ...
comment fait-on ?

EN tout cas, boulot impressionnant ...

**Comment by dbarzin** [comment]
Invalid translation labels in English.
It is fixed.
Thanks,
Didier

**Comment by dbarzin** [comment]
Pour repartir d'une dn vide, c'est dans la doc : https://github.com/dbarzin/deming/blob/main/INSTALL.fr.md dans le section "Remise à zéro"

**Comment by Emeric-hub** [comment]
Merci pour les retours !!!
et comme on dit ... RTFM, dsl pour ca ... :-p

**Comment by Emeric-hub** [comment]
oups, trop rapide... j'ai encore le soucis en tirant la derniere release du repo...

**Comment by dbarzin** [comment]
???
