### ISSUE TITLE
Possible shift between Score, Note, and Action Plan in the Controls export

### ISSUE THREAD

**Issue by thibaudpeter** [dbarzin/deming#48]
![image](https://github.com/dbarzin/deming/assets/50097772/6bc18ca7-1afa-40da-87a5-a2b02909ab71)

In Report > Export Data > Controls, in the excel file, the columns have shifted at the end.
The result of Note is not present,
The result of Score should be in the **Note** column, 
The result of Note should be in the **Action Plan** column

**Comment by dbarzin** [comment]
Fixed ! 
Thanks,
Didier

**Comment by dbarzin** [comment]
Could you have a look at the definitions here : https://dbarzin.github.io/deming/index.fr/#definitions

**Comment by thibaudpeter** [comment]
ok, got it :)
Thanks
