### ISSUE TITLE
Add HTML support in security Measures

### ISSUE THREAD

**Issue by GBues** [dbarzin/deming#49]
Hi,

It would be great to be able to use HTML in security mesures, especialy for the objectif, données and model fields. I'd like to use lists and bold. 

Thanks by advance.

**Comment by dbarzin** [comment]
Yes it is possible but then it is difficult to export these fields in Excel and CSV.
You can use some list with minus and for bold it is not possible.

**Comment by dbarzin** [comment]
We have implemented markdown in most text fields.
