### ISSUE TITLE
file vendor/autoload.php missing. 

### ISSUE THREAD

**Issue by m4ri0g** [dbarzin/deming#51]
index.php references a file as shown below. 
https://github.com/dbarzin/deming/blob/bae4d53f813c22e36df0df4fe84ea587615d2d0c/public/index.php#L24

however after a git pull this file is missing and therefore the application cannot be launched. 
see screenshot 
![bug](https://github.com/dbarzin/deming/assets/47281710/d028d2e3-df9b-493e-bc2e-927297a4d188)

**Comment by dbarzin** [comment]
Have you installed composer and run

    composer update

**Comment by dbarzin** [comment]
No answer after two weeks.
