### ISSUE TITLE
Problème installation version 2013

### ISSUE THREAD

**Issue by mly-h** [dbarzin/deming#53]
Bonjour,

J'ai installé deming avec la version ISO 27001:2022 sans soucis. Cependant j'ai voulais aussi avoir une instance avec la version de 2013 sur une autre machine mais j'ai cette erreur lorsque j'exécute la commande : php artisan vendor:publish --all
![image](https://github.com/dbarzin/deming/assets/133865281/2e88f5f7-8806-4c9e-853d-7b6964672dc8)

Une idée du problème ?

**Comment by dbarzin** [comment]
Vous n'avez pas exécuter composer dans le répertoire /var/www/deming
C'est dans le procédure d'installation :
https://github.com/dbarzin/deming/blob/main/INSTALL.fr.md#installation
