### ISSUE TITLE
/login et /logout redirigent vers http://127.0.0.1:8000 au lieu de l'URL configurée

### ISSUE THREAD

**Issue by sjpp** [dbarzin/deming#54]
Bonjour,

Après une installation réussie, j'ai modifié l'URL de Deming pour son URL de production dans le fichier `.env`.
Le port a été modifié de 8000 pour 8060 et la configuration d'Apache est adaptée pour cela (utilisation des directives `ProxyPass` appropriées). Cela fonctionne correctement pour la plupart des liens une fois connecté.
Toutefois, je rencontre deux erreurs à la connexion et déconnexion.

**À la connexion**

La mire de login est fonctionnelle mais après saisie des identifiants, je suis redirigé vers `http://127.0.0.1:8060/` et non pas vers l'URL de prod configurée.

**À la déconnexion**

En cliquant sur "Quitter", je suis redirigé vers `http://127.0.0.1:8060/` et non pas vers l'URL de prod configurée suffixée de `/logout`.
Par ailleurs, au survol du lien "Quitter", je vois que le lien est `http://127.0.0.1:8060`.

Je ne parviens pas à trouver comment corriger cela. La configuration de l'URL est correcte dans le fichier `.env`, il n'y a pas d'enregistrement de l'URL erronée en base de données, j'ai purgé les caches, mis à jour Deming (via la procédure documentée) mais rien n'y fait.

Auriez-vous une piste pour corriger ce problème qui m'éviterai une ré-installation ? Et au pire des cas, une ré-installation réglerait-elle vraiment ce soucis ?
En vous remerciant.

**Comment by dbarzin** [comment]
C'est corrigé dans la dernière version.
