### ISSUE TITLE
Prise en charge du formatage Markdown (ou autre)

### ISSUE THREAD

**Issue by AntoninLep** [dbarzin/deming#55]
### Description de la demande
Bonjour,

Je souhaiterais savoir s'il était possible d'intégrer la prise en charge d'un formatage style Markdown/AsciiDoc, dans les champs texte éditables (exemple : champ modèle et/ou données) ? L'idée est de pouvoir mettre en forme des données comme des liens, listes à puces, listes ordonnées, tableaux, etc.

### Cas d'usage
J'aimerais pouvoir référencer mes procédures/processus de sécurité au sein de mes mesures/contrôles. De plus,si j'ai plusieurs documents à référencer, je voudrais pouvoir les lister "proprement" via une liste, et idéalement pouvoir y accéder directement depuis un lien cliquable. On peut illustrer cet exemple comme suit :

##### On édite le champ "Données" :
```
L’enregistrement de nouveaux utilisateurs se fait suivant les procédures : 

* [Procédure A](lien) ;
* [Procédure B](lien).
``` 
##### Le rendu lors de la visualisation : 
L’enregistrement de nouveaux utilisateurs se fait suivant les procédures : 
* [Procédure A](lien) ;
* [Procédure B](lien).

De la même manière, on peut imaginer référencer une mesure X, au sein d'une mesure Y : ce genre de formatage faciliterait grandement la navigation dans le cadre d'une revue ou d'un audit.

**Comment by dbarzin** [comment]
Utiliser Markdown est probablement la bonne solution. 
Il y a une éditeur Open Source en ligne :  https://stackedit.io/
Une amélioration va être postée prochainement.
Merci pour l'idée !

**Comment by dbarzin** [comment]
C'est en place pour sur le champ objectif.

**Comment by AntoninLep** [comment]
Bonjour Didier,

Merci pour votre réactivité, je viens de tester l'intégration de Parsedown sur le champ **Objectif**, le rendu est top !
Avez-vous prévu d'étendre cette fonctionnalité sur l'ensemble des champs ?

**Comment by dbarzin** [comment]
Bonjour Antoine,

Cela a été fait également sur la champ "plan d'action". Est-ce utile pour les autres champs ? Cela risque de fort surcharger les écrans.

**Comment by AntoninLep** [comment]
Pour notre cas d'usage, je pense que le champ **Données** est assez critique, car c'est ici que nous référençons nos différentes procédures internes. Les autres champs peuvent rester comme ça effectivement, pour éviter une surcharge au niveau de l'interface.

**Comment by AntoninLep** [comment]
Bonjour Didier,

Mes tests sont concluants, je vous remercie d'avoir pris en charge ma demande rapidement. Je me permets de fermer le ticket.

Bonne journée à vous.
