### ISSUE TITLE
Envoie de notification

### ISSUE THREAD

**Issue by mly-h** [dbarzin/deming#56]
Bonjour, j'ai essayé de configurer l'envoie des notifications par mail. Quand je fais le test ca indique qu'un mail a été envoyé à l'adresse renseigné; cependant quand j'ouvre ma boite je ne vois aucun mail test de deming.
![image](https://github.com/dbarzin/deming/assets/133865281/9edf2e4a-81ad-4db2-b466-2e95f01a0741)

**Comment by dbarzin** [comment]
Qu'est-il indiqué dans les logs de l'application : storage/logs/laravel.log lors de la tentative d'envoi ?
Y a-t-il une trace du mail envoyé dans /var/log/mail.log ?

**Comment by mly-h** [comment]
Bonjour merci pour votre réponse.
Il n'y a aucune trace dans mail.log (le fichier n'existe pas). Par rapport au fichier laravel.log voici le contenu:
![image](https://github.com/dbarzin/deming/assets/133865281/575b1276-0866-4cef-aa6b-076a985ea4ba)

**Comment by dbarzin** [comment]
Sur base du fichier laravel.log, l'application n'envoie pas de mail car la condition de fréquence d'envoi n'est pas remplie (probablement pas d'envoi journalier configuré).
Si le fichier mail.log n'existe pas cela signifie sans doute que le relais de mail n'est pas installé/configuré sur votre serveur. Pouvez-vous voir cela avec votre administrateur réseau ?
