### ISSUE TITLE
Notion de (multi)référentiel pour les mesures de sécurité

### ISSUE THREAD

**Issue by AntoninLep** [dbarzin/deming#60]
Bonjour Didier,

Je me permets d'ouvrir ce ticket pour discuter d'une idée d'évolution qui pourrait apporter une certaine flexibilité à l'application, dans sa gestion des mesures de sécurité.

Actuellement, Deming est axée sur la norme ISO 27001, ce qui est une excellente base. Cependant, notre cas d'usage nous amène à envisager la possibilité d'intégrer la notion de "(multi)référentiel". L'idée serait de permettre l'ajout de mesures de sécurité issues d'autres référentiels (HDS, les bonnes pratiques de l'ANSSI, du NIST, mesures issues des bonnes pratiques "communes", etc.) sans créer de doublons.

Concrètement, cela signifierait donner à chaque mesure la capacité de référencer son ou ses référentiels d'origine. Cela permettrait d'éviter la duplication de mesures tout en offrant une visibilité claire sur les référentiels auxquels chaque mesure est associée (relation N:N entre une mesure et un référentiel).

Actuellement, la notion de domaine est utilisée pour référencer un catalogue de mesures, mais elle pourrait ne pas être assez flexible pour répondre pleinement à ce besoin. Bien que la notion d'attributs puisse être utilisée comme solution de contournement, nous croyons qu'une prise en charge plus directe du (multi)référentiel serait une évolution intéressante pour l'application.

Qu'en pensez-vous ? Je reste bien évidemment ouvert à la discussion pour affiner cette idée et explorer les meilleures façons de l'intégrer à l'outil, si vous la trouvez pertinente.

**Comment by AntoninLep** [comment]
Bonjour Didier,

Merci pour les précisions, je crois comprendre l'utilisation des domaines, mais je trouve son utilisation légèrement peu flexible, je m'explique.

L'idée derrière ma réflexion était surtout de pouvoir lier une mesure à plusieurs référentiels/domaines (actuellement, une mesure peut seulement être liée à 1 seul référentiel, si je ne me trompe). Je vais essayer d'illustrer mon propos par un exemple concret. Disons que nous partons d'une base ISO 27001:2022. Lorsque nous arrivons à une certaine maturité, nous souhaitons maintenant "renforcer" nos mesures déjà en place, en ajoutant des mesures issues d'un autre référentiel (la version 5 de SP800-53 du NIST est un très bon exemple).

Dans la pratique, je vais très vite me rendre compte qu'un certain nombre de mesures des deux référentiels (=domaines), se rapprochent fortement, ou sont même parfois identiques. Nous pouvons prendre l'exemple de la mesure 8.24 "Utilisation de la cryptographie" de l'annexe A d'ISO 27001:2022, qui peut très facilement être mappée avec la mesure SC-12 "Cryptographic Key Establishment and Management" du NIST (sp800-53r5). Il serait donc dommage de créer une mesure "spécifique" pour chaque référentiel, qui s’apparenterait plus à un doublon, le plus pratique (à l'usage) serait alors de pouvoir retrouver directement ces 2 référentiels à partir de la mesure initialement créée (quitte à devoir l'adapter, à la marge).

Je pense qu'on peut effectivement faire apparaître une métadonnée au travers d'un ou plusieurs attributs, mais l'idée de pouvoir lier une mesure à plusieurs domaines me semblait plus pertinente. Cela faciliterait la gestion et l'adaptation des mesures partagées entre différents référentiels.

Qu'en pensez-vous ?

**Comment by AntoninLep** [comment]
Bonjour Didier,

Nous avons fait le choix de faire apparaître les référentiels concernés au travers d'un ou plusieurs attributs sur nos mesures.

Cependant, nous nous retrouvons face à une limitation induite dans la construction de la base, je m'explique. Nous souhaitons initialiser une liste d'attributs par référentiels, mais le champ utilisé pour lister les attributs est limité à 512 caractères. Serait-il possible d'augmenter la taille du VARCHAR utilisé dans la table `attributes` ? Ou bien même de transformer ce champ en un champ de type TEXT ?

**Comment by dbarzin** [comment]
Pas de problème, mais peux-tu créer une nouvelle issue sur ce sujet ?

**Comment by AntoninLep** [comment]
Dans ce cas je me permets de fermer celle-ci, la nouvelle issue étant ouverte (cf. [ #82](https://github.com/dbarzin/deming/issues/82)).
