### ISSUE TITLE
Welcome to deming Discussions!

### ISSUE THREAD

**Issue by jfix31** [dbarzin/deming#62]
Hello i am a beginner sorry for my question if it is unrelevant. Is it posible to install Deming on a MAC ? 
I wanted to install virtual box and ubuntu on my mac (not intel but Mac chips) and i could'nt manage to do so. 
Is there a solution ? thank you.

**Comment by dbarzin** [comment]
Yes, it is possible to install Deming on a Mac. It uses PHP, Laravel and mySQL.
These softwares work on Mac. Have a look the web for "how to install Laravel on Mac" and "how to install mySQL on Mac".

**Comment by jfix31** [comment]
That is kind of you. Thank you

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jfix31** [comment]
Hi Didier,
I hope I don’t bother you too much.
I’m on Mac Sonoma 14.1 .(mac chip)

I installed :
Laravel
mysQL
and a container.

What should I do next ?

Is there a roadmap for mac ?
Or another help that I could get to install deming ?

Thank you very much
Best regards
Jérôme
+33 620988816

De : Didier Barzin ***@***.***>
Date : mardi, 19 décembre 2023 à 17:53
À : dbarzin/deming ***@***.***>
Cc : jfix31 ***@***.***>, Author ***@***.***>
Objet : Re: [dbarzin/deming] Welcome to deming Discussions! (Issue #62)

Yes, it is possible to install Deming on a Mac. It uses PHP, Laravel and mySQL.
These softwares work on Mac. Have a look the web for "how to install Laravel on Mac" and "how to install mySQL on Mac".

**Comment by dbarzin** [comment]
Try to follow the Linux installation : https://github.com/dbarzin/deming/blob/main/INSTALL.md

**Comment by jfix31** [comment]
Can I use the same linux command in the terminal ? Thanks

De : Didier Barzin ***@***.***>
Date : vendredi, 22 décembre 2023 à 08:48
À : dbarzin/deming ***@***.***>
Cc : jfix31 ***@***.***>, Author ***@***.***>
Objet : Re: [dbarzin/deming] Welcome to deming Discussions! (Issue #62)

Try to follow the Linux installation : https://github.com/dbarzin/deming/blob/main/INSTALL.md

**Comment by dbarzin** [comment]
You may try, most command should be the same.

**Comment by jfix31** [comment]
Hi Didier,

I am almost done. I’ve succeed I think to install everything.
I am just blocked with the credentials.

I put :
***@***.***

demPasssword-123

and it doesn’t work.
Any idea please ?

Thank you very much for your patience.

Have a nice christmas’ day !
Jérôme


De : Didier Barzin ***@***.***>
Date : vendredi, 22 décembre 2023 à 12:14
À : dbarzin/deming ***@***.***>
Cc : jfix31 ***@***.***>, Author ***@***.***>
Objet : Re: [dbarzin/deming] Welcome to deming Discussions! (Issue #62)

You may try, most command should be the same.

**Comment by dbarzin** [comment]
The password to enter the web application is "admin".

**Comment by jfix31** [comment]
Merci Didier. Et bravo ! Quel travail réalisé !
Je suis en train de me certifier, et cela va beaucoup m’aider à retenir et m’exercer pour un premier client en Iso 27001.

Merci et très bonnes fêtes !
Jérôme FICAT
De : Didier Barzin ***@***.***>
Date : lundi, 25 décembre 2023 à 11:08
À : dbarzin/deming ***@***.***>
Cc : jfix31 ***@***.***>, Author ***@***.***>
Objet : Re: [dbarzin/deming] Welcome to deming Discussions! (Issue #62)

The password to enter the web application is "admin".
