### ISSUE TITLE
Problème de bascule en langue française

### ISSUE THREAD

**Issue by Yoshimi40** [dbarzin/deming#64]
Bonjour,
Je souhaite tout d'abord à vous remercier pour le travail fourni. Je suis en train de tester votre outil dans le cadre de notre certification ISO27001.
Voici le problème que je rencontre.
J'ai un souci de traduction de la norme d'anglais vers le français. Quand je choisis la langue française, Seule l'interface est traduite. Les domaines et mesures restent en anglais.
J'ai réinstallé entièrement l'outil mais le problème reste entier (fresh install).

En vous remerciant par avance.

**Comment by dbarzin** [comment]
L'interface est traduite automatiquement mais pas les mesures de sécurité.
Pour repartir sur une base de données avec les mesures en français, voici les commandes  :
Effacer la base de données :

    LANG=fr php artisan migrate:fresh --seed

Pour importer la base de données avec les mesures de sécurité de la norme 27001:2022

    LANG=fr php artisan db:seed --class=AttributeSeeder
    LANG=fr php artisan db:seed --class=DomainSeeder
    LANG=fr php artisan db:seed --class=MeasureSeeder

Cela se trouve dans la documentation en français ici : https://github.com/dbarzin/deming/blob/main/INSTALL.fr.md

**Comment by Yoshimi40** [comment]
Merci beaucoup cela fonctionne parfaitement.
