### ISSUE TITLE
“question” Accès web en https

### ISSUE THREAD

**Issue by cyrus951** [dbarzin/deming#65]
Bonjour à tous,

Malgré de nombreuse recherche je suis confronté à un soucis d'accès au front deming en https.
j'obtiens un jolie ERROR_CONNEXION_CLOSED
j'ai bien ajouté le fichier de conf apache pour l'accès https, le chemin vers les certificats sont tous ok, je vous avoues ne pas trop savoir ce que j'aurais bien pu oublier.

Je vous remercie par avance pour toute l'aide que vous pourrez m'apporter et m'excuse par avance pour la question de noob :)

**Comment by dbarzin** [comment]
Cela ressemble à un problème de configuration Apache.
Tu peux essayer de suivre le configuration HTTPS de Mercator : https://github.com/dbarzin/mercator/blob/master/INSTALL.md#https C'est le même framework qui est utilisé.

**Comment by dbarzin** [comment]
Pase de réponse.
