### ISSUE TITLE
Attempt to read property "owners" on null

### ISSUE THREAD

**Issue by Cronycs** [dbarzin/deming#7]
Bonjour Didier,
Tout d'abord je vous remercie de nous partager cette application qui m'a l'air prometteuse !
Je suis en phase de test et je rencontre un soucis bloquant, lorsque j'essaie de planifier une nouvelle Mesure, j'obtiens l'erreur suivante :
https://flareapp.io/share/Lm8MLBVP#stack
Je rencontre le même soucis avec les mesures importées ou en partant sur une BDD de zéro.
Est-ce que j'aurai raté quelque chose lors de l'installation de la solution?
En vous remerciant pour votre aide.

**Comment by dbarzin** [comment]
Corrigé, merci.
Didier

**Comment by Cronycs** [comment]
Bonjour,
Je vous confirme que le soucis est bien résolu, merci ! :)
