### ISSUE TITLE
Problème notification

### ISSUE THREAD

**Issue by mangoDC** [dbarzin/deming#71]
Bonjour, 

Après avoir effectué des changements au niveau du localhost name(dns), je ne reçois plus de notifications lorsque je planifie un contrôle ce qui était possible avant modification.

Même avec la commande suivante rien ne se passe php artisan deming:send-notifications.

Pourtant le test d'envoi de mail lui fonctionne bien dans Notifications configuration.

Si je reprends la commande exécutée par la crontab :
/var/www/deming$ php artisan schedule:run

INFO No scheduled commands are ready to run.

logs obtenu avec la commande larevel.log : 
[2024-02-29 12:07:55] ISMS.DEBUG: SendNotifications - Start.
[2024-02-29 12:07:55] ISMS.DEBUG: SendNotifications - day 25
[2024-02-29 12:07:55] ISMS.DEBUG: SendNotifications - check
[2024-02-29 12:07:55] ISMS.DEBUG: SendNotifications - DONE.
[2024-02-29 12:45:27] ISMS.DEBUG: SendNotifications - Start.
[2024-02-29 12:45:27] ISMS.DEBUG: SendNotifications - day 25
[2024-02-29 12:45:27] ISMS.DEBUG: SendNotifications - check
[2024-02-29 12:45:28] ISMS.DEBUG: SendNotifications - DONE.
[2024-02-29 12:48:28] ISMS.DEBUG: SendNotifications - Start.
[2024-02-29 12:48:28] ISMS.DEBUG: SendNotifications - day 25
[2024-02-29 12:48:28] ISMS.DEBUG: SendNotifications - check
[2024-02-29 12:48:28] ISMS.DEBUG: SendNotifications - DONE.

**Comment by dbarzin** [comment]
Le code se trouve ici : https://github.com/dbarzin/deming/blob/main/app/Console/Commands/SendNotifications.php

Selon la fréquence, les notification ne sont envoyées que certains jours :

```php
    private function needCheck()
    {
        $check_frequency = config('deming.notification.frequency');

        return // Daily
            ($check_frequency === '1') ||
            // Weekly
            (($check_frequency === '7') && (Carbon::today()->dayOfWeek === 1)) ||
            // Every two weeks
            (($check_frequency === '15') && (Carbon::today()->dayOfWeek === 15)) ||
            // Monthly
            (($check_frequency === '30') && (Carbon::today()->day === 1));
    }
```

**Comment by dbarzin** [comment]
Des messages de logs ont été ajoutés pour mieux pouvoir tracer ce qui se passe dans cette classe.

**Comment by mangoDC** [comment]
La fréquence est identique à votre code, une notification doit etre envoyé tous les jours à minuit. 
Comment puis-je avoir voir les logs lié à ce qui se passe dans cette commande ?

**Comment by mangoDC** [comment]
après vérification des logs je constate qu'il y a un no check cela peut-il etre la cause du problème ? 
![image](https://github.com/dbarzin/deming/assets/101676924/3ae59973-e5d2-4079-be2a-234aec1677fc)
``

**Comment by dbarzin** [comment]
Tu n'as pas la dernière version du code. Peux-tu mettre à jour et recommencer ?

**Comment by mangoDC** [comment]
Lorsque je fais un git pull je recois le message d'erreur suivant : 
![image](https://github.com/dbarzin/deming/assets/101676924/34b787dd-e8fb-4b46-a07d-d925e2ef5fe7)

**Comment by dbarzin** [comment]
OK, "rm composer.lock"

**Comment by mangoDC** [comment]
Mise à jour effectué mais le résultat est le même, la notification planifié pour aujourd'hui ne s'envoie pas même avec la commande   php artisan deming:send-notifications.
![image](https://github.com/dbarzin/deming/assets/101676924/8709bf91-d400-4306-a818-b3cbd33be06f)

**Comment by dbarzin** [comment]
Il y a un problème de cache, il semble que ce ne soit pas la dernière version du code qui est exécuté. 
Le log "no check" a été remplacé par un autre message dans le code : https://github.com/dbarzin/deming/blob/main/app/Console/Commands/SendNotifications.php

Peux-tu essayer de lancer cette commande :

    php artisan optimize:clear

La commande d'envoi de mail est exécutée une fois par jour via le crontab.
Cela se trouve dans la procédure d'installation : https://github.com/dbarzin/deming/blob/main/INSTALL.fr.md#sheduler

**Comment by mangoDC** [comment]
alors la fréquence est passé à 0.
![image](https://github.com/dbarzin/deming/assets/101676924/3c127020-3eb2-4f9e-bac5-78765f3a8f78)

**Comment by mangoDC** [comment]
Problème résolu merci pour votre aide.
