### ISSUE TITLE
Non sauvegarde des ATTRIBUTS lors de la création d'une MESURE

### ISSUE THREAD

**Issue by cpo-c** [dbarzin/deming#72]
Lors de la création d'une mesure, les attributs ne sont pas sauvegardés.
Le workaround actuel: modifier la mesure et saisir les attributs, la sauvegarde de la modification fonctionne.

**Comment by dbarzin** [comment]
Corrigé ici : https://github.com/dbarzin/deming/commit/1fbe60cc01acc5e86057d45ffa07c5f2f9f9e707

**Comment by cpo-c** [comment]
Cela fonctionne parfaitement, merci!
