### ISSUE TITLE
Demande de fonctionnalité web UI - Intégration gestion de language iso 27001 dans l'interface web

### ISSUE THREAD

**Issue by protocolpaladin** [dbarzin/deming#76]
L'idée et de rendre directement disponible le changement de language iso27001 via l'interface web en ajoutant aussi dans le schema et les tables une colonne supplémentaire pour identifier le language a appliquer et pouvoir basculer dynamiquement entre une langue à une autre. Cela permettrait une evolution du language à posteriori et aussi si l'application à des nouveaux languages un jour un peu comme le système dynamique du language de l'interface web de l'application

**Comment by dbarzin** [comment]
Une colonne supplémentaire par langue, cela risque de faire beaucoup de colonnes. Pour le moment, je préfère rester sur une langue à la fois, c'est généralement ce qui est fait dans toutes les organisations. Le SMSI est mis en place dans une langue choisie lors de sa mise en place.

**Comment by protocolpaladin** [comment]
Pas de soucis, mais dans le côté multinational ça aurai pu servir et aider certains interlocuteurs de basculer de langue.

**Comment by dbarzin** [comment]
Tu peux toujours mettre le texte dans les deux langues dans un même champ.
