### ISSUE TITLE
Supprimer un contrôle

### ISSUE THREAD

**Issue by eglyn** [dbarzin/deming#8]
Bonjour :)

Nous sommes en train de tester cet outil qui semble bien pratique, mais une question se pose lors de nos tests: comment supprimer un contrôle ? 

merci d'avance de votre réponse :)

**Comment by dbarzin** [comment]
Voilà trois ans que j'utilise Deming sans jamais avoir eu besoin de supprimer un contrôle.
Cela va être implémenté cette semaine. Il faudra aller sur le contrôle et être administrateur pour pouvoir supprimer un contrôle.

**Comment by dbarzin** [comment]
C'est en place !

**Comment by eglyn** [comment]
Wow, super rapide, merci beaucoup, on va continuer nos tests !
