### ISSUE TITLE
Modification du champ `values` de la table `attributes`

### ISSUE THREAD

**Issue by AntoninLep** [dbarzin/deming#82]
Bonjour Didier,

Nous souhaitons initialiser des listes d'attributs qui dépassent la limite actuellement en place (`VARCHAR(512)`). Serait-il possible d'augmenter la taille du VARCHAR utilisé dans la table `attributes` ? Ou à défaut, de transformer ce champ en un champ de type `TEXT` ?

Pour avoir un ordre d'idée, notre plus longue liste d'attributs fait environ 2900 caractères.

**Comment by dbarzin** [comment]
Le champ va être modifié.

**Comment by dbarzin** [comment]
Le champ a été modifié en varchar(4096) ici : https://github.com/dbarzin/deming/commit/75cc7bde3586ee4aff283415bd950f668190ea46

**Comment by AntoninLep** [comment]
Je viens de déployer la MàJ sur mon instance, tout est bon, merci pour ta réactivité !

Juste par curiosité, pourquoi ne pas choisir un champ de type `TEXT` directement, plutôt que d'augmenter la taille à 4096 ?

**Comment by dbarzin** [comment]
Oui, effectivement, mais en poussant ce raisonnement plus loin, on pourrait aussi utiliser des champs `TEXT` partout.
Donc, bien qu'il n'y ait pas de raison particulière, la taille maximale d'un `VARCHAR` étant de 65535 caractères, j'ai appliqué le principe [KISS](https://fr.wikipedia.org/wiki/Principe_KISS) et changé la taille de ce champ de 512 à 4096 caractères.

**Comment by AntoninLep** [comment]
Effectivement, parfois il vaut mieux faire au plus simple, merci pour les précisions :)
