### ISSUE TITLE
Controls not shown in list

### ISSUE THREAD

**Issue by dbarzin** [dbarzin/deming#87]
Dear community,

I've just installed Deming as I want to use it in my day2day job.

I've done a test a few month ago, and I really appreciate Deming.

However, within my new instance freshly installed with ISO 27002:2022, I can't see all controls into the control list window...

![image](https://github.com/dbarzin/deming/assets/16591723/51bffcc2-a572-4f77-b81a-93e570b30c0d)

But normally control are presents, as per this screen:

![image](https://github.com/dbarzin/deming/assets/16591723/0d215140-0e3e-4926-bf81-7b398b80ffd7)

When I use the Search tool, I can find controls:

![image](https://github.com/dbarzin/deming/assets/16591723/7b34b5a5-47b4-4296-a7ab-ce2ba9611e93)

Then I can have access to them:

![image](https://github.com/dbarzin/deming/assets/16591723/004c472a-a321-4966-9b32-6f722d0af575)

I've reinstalled 3 times following the procedure, however this behavior is still present.

Can you tell me where I'm wrong?

Regards

_Originally posted by @danje57 in https://github.com/dbarzin/deming/discussions/15#discussioncomment-9383010_

**Comment by dbarzin** [comment]
I have to check.

**Comment by dbarzin** [comment]
I have not be able to reproduced your problem as described. However, another related issue has been fixed here : https://github.com/dbarzin/deming/commit/a9e346a0628fe9bcfd9365f7a668fc436ff87a98

**Comment by danje57** [comment]
When you select a domain in the control list, do you get all controls of the selected domain ?
==> No

I'll try a new fresh install with your fix.

**Comment by danje57** [comment]
It works fine!

Now I can see all Controls :)

One more question, did you test deming with Ubuntu 23.10 (64bit)?

(Normally I could create PCI DSS v4.0 template)

**Comment by dbarzin** [comment]
Deming has not been tested with Ubuntu 23.10, but it should work fine.
