### ISSUE TITLE
problème de modele

### ISSUE THREAD

**Issue by ygrekconsutling** [dbarzin/deming#88]
Lorsque je télécharge le modèle de base de forme de contrôle et que je le reupload ensuite, a chaque fois que je veut commencer un point de contrôle en allant dans le détail d'une tache planifié et que je clique sur télécharger le modèle prérempli je me retrouve avec un fichier word (docx) corrompu
Debian, Apache2, php 8.2

**Comment by dbarzin** [comment]
Y a-t-il une erreur dans les logs (storage/logs/laravel.log) ?
Avec quoi ouvres-tu le fichier (OpenOffice, Word...) ?
Peux-tu poster le modèle et le fichier corrompu ici ?

**Comment by ygrekconsutling** [comment]
Au niveau des logs rien de nouveau, j'ai seulement les local debug lié a l'injection des mesures de tests liés aux referentiels
J'ouvre le fichier avec Word 2019

le modèle et le fichiers corrompu sont là: 
[corupted.docx](https://github.com/dbarzin/deming/files/15370855/corupted.docx)
[modele de controle.docx](https://github.com/dbarzin/deming/files/15370858/modele.de.controle.docx)

merci pour le retour

**Comment by dbarzin** [comment]
Merci pour cette analyse. Deming n'utilise pas Libre Office ni Open Office pour générer les fichiers, mais la librairie PHPOffice. Le problème ne vient pas de là. 

De mon côté, j'arrive à générer une fiche de contrôle à partir du modèle fourni : 
[control-5.04-20240520.docx](https://github.com/dbarzin/deming/files/15376032/control-5.04-20240520.docx)

Peux-tu essayer de supprimer les variables dans le modèle pour identifier celle qui pose un problème puis sans doute le texte dans cette variable qui génère un document invalide.

Il n'était pas prévu de mettre le champ _observations_ dans le modèle bien que cela ne pose pas de problème.
L'idée étant que les observations sont à mettre directement dans le document.

Si tu souhaites aller plus loin, le code à modifier se trouve dans app/HTTP/Controllers/ControlController.php dans la fonction template()

**Comment by ygrekconsutling** [comment]
c'est exactement ce que j'ai fait en supprimant la variable attribute du modèle comme j'ai mis en note en dernier paragraphe

**Comment by ygrekconsutling** [comment]
non, je n'ai pas encore eu le temps de m'y mettre, je regarderais ça tout a l'heure. J'ai quand même tenté une install sur un autre serveur au cas où et sans tenter de toucher au modèle de base, la generation se fait bien directement sans encombres, je vais mettre un gros try catch sur le fichier et quelques debugger pour tracer d'où ça vient

**Comment by ygrekconsutling** [comment]
Ok, so finnally got to the end of the "error",
I compared the 2 instance and found out a thing very different: on the page detail itself the attribute aren't present on my instance while on the second it's present, i suppose their was an issue with the installation (suppose because i can't see where i can go wrong) and then when adding a little json encode to the control->attribute (line 1243) to dump the variable itself in the file it's an empty string variable, i think it simply crashed the generation due to no data found or something like that :)
