### ISSUE TITLE
Question : API prévue ?

### ISSUE THREAD

**Issue by standard3** [dbarzin/deming#9]
Bonjour,

Votre application semble très intéressante, est-il prévu d'implémenter une API pour communiquer avec le backend ?

Merci

**Comment by dbarzin** [comment]
Il n'est pas prévu d'implémenter une API mais ce n'est pas difficile à faire avec le framework Laravel.
Peux-tu décrire le cas d'utilisation ?

**Comment by dbarzin** [comment]
Magnifique ce cas d'utilisation. L'API sera disponible ce lundi au plus tard !

**Comment by cynikkk** [comment]
Génial, je surveille le projet alors ;)

**Comment by dbarzin** [comment]
Un peu de retard dans la livraison de l'API. Cela renvoie une erreur 401 pour l'instant.

**Comment by dbarzin** [comment]
:tada: L'API est disponible ! La documentation se trouve ici https://dbarzin.github.io/deming/api.fr/
