### ISSUE TITLE
MPA5.2 and MVSP referentials

### ISSUE THREAD

**Issue by charlesgoyard** [dbarzin/deming#90]
Hi,
I submitting the _Motion Picture Association_ and _Minimum Viable Security Product_ referentials for inclusion into Deming.
I wanted to make a pull request but noticed the `storage` directory is in `.gitignore`, so maybe that's not the proper way.

* [MPA-5.2-Best-Practices.xlsx](https://github.com/user-attachments/files/15836081/MPA-5.2-Best-Practices.xlsx)
* [mvsp-3.0.xlsx](https://github.com/user-attachments/files/15836082/mvsp-3.0.xlsx)
* [README.md](https://github.com/user-attachments/files/15836083/README.md) (short table to describe the files)

Thanks !
Charles

**Comment by dbarzin** [comment]
Thanks you for this contribution, you may propose a pull request !
