### ISSUE TITLE
Consistency of attribute tags in ISO27001-2022

### ISSUE THREAD

**Issue by charlesgoyard** [dbarzin/deming#91]
Hi,

I noticed there are some duplicates in the attributes in ISO27001:2002 English. For example, _Supplier_Relationships_Security_ and _Security_of_supplier_relations_.

I made a cleanup in the XLSX file, attached. It's not 100% clean but more consistent, if you want to review and include it.

[ISO27001-2022.en.xlsx](https://github.com/user-attachments/files/15836246/ISO27001-2022.en.xlsx)

**Comment by dbarzin** [comment]
Thanks, I will update the document !
