### ISSUE TITLE
ISMS Steering Report is output in French

### ISSUE THREAD

**Issue by peteryusuf** [dbarzin/deming#94]
I just ran a report and the headers are in french. 
[pilotage-2024-07-10.docx](https://github.com/user-attachments/files/16158521/pilotage-2024-07-10.docx)

<img width="547" alt="image" src="https://github.com/dbarzin/deming/assets/68426585/1a714e6e-495d-4f05-8f8e-7df0210b8b6a">

**Comment by peteryusuf** [comment]
Actually not just the report. Appears some sections of the site are not translated to English at all.

**Comment by dbarzin** [comment]
You may change the steering report template in the section Confguration -> Document to match not only your language, but also your company layout. For the parts not translated, it is not made by purpose. Could you give me the sections that are not translated ?
Thanks,
Didier
